export const GAME_SCHEMA_VERSION = 'newcore-save-v2.4.20';

export function createInitialGameState(mapAdapter) {
  return {
    version: GAME_SCHEMA_VERSION,
    project: 'Terra Nova / SIMURB NewCore',
    mode: 'title',
    selectedTool: null,
    selectedZoneType: 'residential',
    selectedZoneDensity: 'low',
    selectedTerrainBrush: 'trees',
    terrainBrushSize: 18,
    tmpeMode: 'signals',
    tmpeLaneIndex: -1,
    tmpeLaneClass: 'bus',
    settings: {
      gameMode: 'sandbox',
      testTrafficEnabled: true,
      dayNightCycleEnabled: true
    },
    viewLayers: {
      buildings: true,
      zones: true,
      vehicles: true,
      grid: false,
      trafficControls: true,
      events: true
    },
    trafficControls: {
      autoSignals: true,
      nodes: {},
      segments: {},
      version: '2.4.20'
    },
    buildOptions: {
      roadType: 'street',
      roadLanes: 2,
      roadElevation: 0,
      roadSpeed: 50,
      roadGeometry: 'smooth',
      roadDirection: 'twoWay',
      roadLaneClass: 'general',
      roadSnap: true,
      roadZoneEdges: true,
      roadZoneLeft: true,
      roadZoneRight: true,
      roadAutoZoneType: 'residential',
      roadParkingAllowed: false,
      roadBusLane: false,
      railKind: 'double',
      railMode: 'train',
      railGeometry: 'smooth',
      railElevation: 0,
      railSpeed: 90,
      railSnap: true,
      zoneSide: 'both'
    },
    mapConfig: mapAdapter.getConfig(),
    mapStats: mapAdapter.getStats(),
    simulation: {
      paused: true,
      speed: 1,
      money: 250000,
      population: 0,
      jobs: 0,
      passengersPerHour: 0,
      congestion: 0,
      vehicleCongestion: 0,
      modalShare: { car: 100, transit: 0, bike: 0 },
      unemploymentRate: 0,
      favelaPressure: 0,
      comfortPenalty: 0,
      trafficVehicles: 0,
      activeBuses: 0,
      activeTrains: 0,
      avgTrafficSpeed: 0,
      transitStops: 0,
      busLines: 0,
      transitCoverage: 0,
      transitRidership: 0,
      transitOccupancy: 0,
      railStations: 0,
      railLines: 0,
      railRidership: 0,
      railOccupancy: 0,
      fareRevenueHourly: 0,
      transitExpensesHourly: 0,
      busFareRevenueHourly: 0,
      busTransitExpensesHourly: 0,
      railFareRevenueHourly: 0,
      railExpensesHourly: 0,
      demand: {
        residential: 0.62,
        commercial: 0.44,
        industrial: 0.40
      },
      satisfaction: 72,
      landValue: 38,
      employmentRate: 0,
      housingPressure: 0,
      jobPressure: 0,
      commercialPressure: 0,
      industrialPressure: 0,
      taxIncomeHourly: 0,
      serviceExpensesHourly: 0,
      infrastructureExpensesHourly: 0,
      transitBalanceHourly: 0,
      netIncomeHourly: 0,
      growthEvents: 0,
      activeEvents: 0,
      upgradedBuildings: 0,
      day: 1,
      hour: 6,
      minute: 0,
      history: []
    },
    networks: {
      roads: [],
      roadNodes: [],
      rails: [],
      railNodes: []
    },
    zoning: [],
    zoneGrid: [],
    buildings: [],
    citizens: [],
    vehicles: [],
    events: {
      active: [],
      history: []
    },
    transitStops: [],
    transitLines: [],
    transitDraft: { mode: 'bus', stopIds: [] },
    railStations: [],
    railDraft: { mode: 'rail', stationIds: [] },
    assetPacks: {
      buildings: []
    },
    inspector: {
      text: 'Nada selecionado.'
    },
    legacyBridge: {
      imported: true,
      source: 'simurban modular.zip',
      strategy: 'NewCore usa o gerador como host e reaproveita lógica/sistemas úteis por adaptação modular.',
      adaptedTargets: [
        'construção por nós/segmentos',
        'RoadCore básico',
        'zoneamento vinculado às vias',
        'economia/simulação simplificada',
        'transporte público inicial',
        'trilhos iniciais',
        'save/load JSON novo',
        'loteamento por perfil de zona',
        'packs 3D procedurais separados',
        'pintura de zona por arraste',
        'upgrade básico de vias',
        'limpeza de lotes órfãos',
        'geometria visual suave por continuidade de nós',
        'detalhes iniciais de elevado e túnel',
        'faixas de pedestres e linhas de retenção',
        'setas de direção sem losango em mão dupla',
        'realce de upgrade/demolição por preview',
        'limpeza de nós duplicados e segmentos inválidos',
        'classes de faixa por segmento',
        'corredor de ônibus/emergência/serviços/misto/ciclovia/estacionamento visual',
        'grafo rodoviário respeitando mão única',
        'preparação da IA para permissões por tipo de veículo',
        'Dijkstra rodoviário por tipo de veículo respeitando mão única e classe de faixa',
        'rotas casa-trabalho com origem/destino em construções',
        'congestionamento básico por carga de segmento',
        'telemetria de tráfego no HUD',
        'renderização de infraestrutura v1.5 com asfalto texturizado, base de via, bordas e calçadas com guia',
        'trilhos v1.5 com lastro de brita, dormentes dedicados e trilho duplo visual',
        'remoção dos nós debug permanentes da renderização de vias/trilhos',
        'transporte público v1.6 com paradas de ônibus editáveis, linhas por paradas, auto-linha e métricas de lotação/receita',
        'renderização inicial de pontos, abrigos, placas e traçado de linha de ônibus',
        'Rail/Metro Alpha v1.7 com estações ferroviárias editáveis, linhas por estação, auto-linha, métricas e trens por rota real',
        'Economy/RCI Alpha v1.8 com demanda R/C/I, satisfação, impostos, custos, saldo horário e evolução inicial de edifícios',
        'Infra render v2.1 com corpo de asfalto contínuo, marcações coladas, cruzamentos integrados e lastro/trilhos curvos visíveis, mantendo simulação/economia alinhadas ao .md e arquitetura modular',
        'Paridade funcional v2.4.19: semáforos automáticos em cruzamentos complexos, supressão manual por TMPE, headway simples entre veículos, resposta emergencial a eventos e composições ferroviárias por modo (trem/metrô/VLT)',
        'Paridade funcional v2.4.20: conectores faixa-a-faixa por nó, fases manuais de semáforo e prioridade de fluxo por via larga/rápida com impacto em rota, faixa e velocidade'
      ]
    }
  };
}

export function serializeGameState(state, mapAdapter) {
  return {
    ...state,
    mapConfig: mapAdapter.getConfig(),
    mapStats: mapAdapter.getStats(),
    exportedAt: new Date().toISOString()
  };
}
